var json_CIBELESSEVILLASANTAFE_20 = {
"type": "FeatureCollection",
"name": "CIBELESSEVILLASANTAFE_20",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Cibeles -> Sevilla -> Santa Fe", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.1662049, 19.4195954 ] } },
{ "type": "Feature", "properties": { "Name": "Cibeles -> Sevilla -> Santa Fe", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.1717935, 19.4222573 ] } },
{ "type": "Feature", "properties": { "Name": "Cibeles -> Sevilla -> Santa Fe", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.2541491, 19.3765308 ] } },
{ "type": "Feature", "properties": { "Name": "Cibeles -> Sevilla -> Santa Fe", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.2596056, 19.3732942 ] } },
{ "type": "Feature", "properties": { "Name": "Cibeles -> Sevilla -> Santa Fe", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.2606789, 19.3677142 ] } },
{ "type": "Feature", "properties": { "Name": "Cibeles -> Sevilla -> Santa Fe", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.2635798, 19.3663845 ] } },
{ "type": "Feature", "properties": { "Name": "Cibeles -> Sevilla -> Santa Fe", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.2708211, 19.3642219 ] } },
{ "type": "Feature", "properties": { "Name": "Cibeles -> Sevilla -> Santa Fe", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.2776355, 19.357463 ] } },
{ "type": "Feature", "properties": { "Name": "Cibeles -> Sevilla -> Santa Fe", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.2738635, 19.3574854 ] } },
{ "type": "Feature", "properties": { "Name": "Cibeles -> Sevilla -> Santa Fe", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.2592569, 19.3656751 ] } }
]
}
