var json_MUNDOESANTAFECHAMAPA_12 = {
"type": "FeatureCollection",
"name": "MUNDOESANTAFECHAMAPA_12",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": "Mundo E -> Santa Fe (AM) Chamapa", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.2637094, 19.3665001 ] } },
{ "type": "Feature", "properties": { "Name": "Mundo E -> Santa Fe (AM) Chamapa", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.2594319, 19.3733682 ] } },
{ "type": "Feature", "properties": { "Name": "Mundo E -> Santa Fe (AM) Chamapa", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.2530707, 19.387168 ] } },
{ "type": "Feature", "properties": { "Name": "Mundo E -> Santa Fe (AM) Chamapa", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.2252722, 19.5262251 ] } },
{ "type": "Feature", "properties": { "Name": "Mundo E -> Santa Fe (AM) Chamapa", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.2332533, 19.5156892 ] } },
{ "type": "Feature", "properties": { "Name": "Mundo E -> Santa Fe (AM) Chamapa", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.2468793, 19.5188522 ] } },
{ "type": "Feature", "properties": { "Name": "Mundo E -> Santa Fe (AM) Chamapa", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.259107, 19.5175934 ] } },
{ "type": "Feature", "properties": { "Name": "Mundo E -> Santa Fe (AM) Chamapa", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.2776355, 19.357463 ] } },
{ "type": "Feature", "properties": { "Name": "Mundo E -> Santa Fe (AM) Chamapa", "descriptio": null, "timestamp": null, "begin": null, "end": null, "altitudeMo": null, "tessellate": "-1", "extrude": "0", "visibility": "-1", "drawOrder": null, "icon": null }, "geometry": { "type": "Point", "coordinates": [ -99.2738962, 19.3574617 ] } }
]
}
